### ISSUE TITLE
Couple small bugs

### ISSUE THREAD

**Issue by Geekmakes** [XZot1K/HyperDrive#1]
Hey, just updated to 1.14 and the latest HyperDrive lotta stuff changed. I've been editing the config and I can't get /hyperdrive reload to work causes this: https://pastebin.com/CSKGgC6Q Also "/tpahere (name)" is defaulting to essentials, it's acting like that command doesn't exist anymore? Oh and I've had reports of the /tpa command not tab completing for players names (works fine for oped players). Thanks! really like this update.

**Comment by XZot1K** [comment]
Thank you for the reports! The server dump was due to many warps being saved at a single time from the reload. I'll swap the command over to async. If you are using EssentialsEx it may be simply overriding HyperDrive's instance since it is a lightweight feature currently to allow users to remove the commands if needed. This also goes for the tab completion it wasn't added yet to sort of making everyone happy since people still like to use essentials for standalone teleportations! I will take a look at everything and make adjustments accordingly!
